AWSTemplateFormatVersion: "2010-09-09"
Description: "Amply Artist Setup - Creates S3, CloudFront, and IAM resources, then registers with Amply"

Parameters:
  ArtistName:
    Type: String
    Description: Artist name (lowercase, no spaces)
    AllowedPattern: "^[a-z0-9-]+$"

  ArtistId:
    Type: String
    Description: Unique artist identifier

  AmplyAPIEndpoint:
    Type: String
    Default: "https://u7q5tko85l.execute-api.eu-north-1.amazonaws.com/complete-artist-setup"
    Description: Amply API endpoint for callbacks

  WaveformAnalyzerLambdaArn:
    Type: String
    Default: "arn:aws:lambda:eu-north-1:596430611327:function:waveform-analyzer"
    Description: ARN of the waveform-analyzer Lambda function

Resources:
  # IAM Role for the setup Lambda
  SetupLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: AmplySetupPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:CreateBucket"
                  - "s3:PutBucketPolicy"
                  - "s3:PutBucketVersioning"
                  - "s3:PutBucketAcl"
                  - "s3:PutBucketCors"
                  - "s3:PutBucketNotification"
                  - "cloudfront:CreateCloudFrontOriginAccessIdentity"
                  - "cloudfront:CreateDistribution"
                  - "cloudfront:GetDistribution"
                  - "iam:CreateRole"
                  - "iam:PutRolePolicy"
                  - "lambda:AddPermission"
                Resource: "*"

  # Lambda function that creates all resources
  SetupLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !GetAtt SetupLambdaRole.Arn
      Timeout: 300
      Environment:
        Variables:
          AMPLY_API_ENDPOINT: !Ref AmplyAPIEndpoint
          WAVEFORM_ANALYZER_LAMBDA_ARN: !Ref WaveformAnalyzerLambdaArn
      Code:
        ZipFile: |
          const { S3Client, CreateBucketCommand, PutBucketPolicyCommand, PutBucketCorsCommand } = require('@aws-sdk/client-s3');
          const { CloudFrontClient, CreateCloudFrontOriginAccessIdentityCommand, CreateDistributionCommand } = require('@aws-sdk/client-cloudfront');
          const { IAMClient, CreateRoleCommand, PutRolePolicyCommand } = require('@aws-sdk/client-iam');
          const { STSClient, GetCallerIdentityCommand } = require('@aws-sdk/client-sts');
          const https = require('https');

          const region = 'eu-north-1';
          const s3 = new S3Client({ region });
          const cloudfront = new CloudFrontClient({ region });
          const iam = new IAMClient({ region });
          const sts = new STSClient({ region });

          exports.handler = async (event) => {
            try {
              console.log('Event:', JSON.stringify(event));
              
              // For Custom resource invocations
              const artistName = event.ResourceProperties?.ArtistName || event.ArtistName;
              const artistId = event.ResourceProperties?.ArtistId || event.ArtistId;
              let accountId = event.Account;
              
              // Get account ID if not provided
              if (!accountId) {
                try {
                  const identity = await sts.send(new GetCallerIdentityCommand({}));
                  accountId = identity.Account;
                } catch (e) {
                  console.error('Failed to get account ID:', e);
                  accountId = 'unknown';
                }
              }
              
              console.log(`Creating resources for artist: ${artistName}`);
              
              if (!artistName) {
                throw new Error('ArtistName is required');
              }
              
              // Step 1: Create S3 bucket
              const bucketName = `amply-${artistName}-${accountId}`;
              console.log(`Creating S3 bucket: ${bucketName}`);
              
              await s3.send(new CreateBucketCommand({
                Bucket: bucketName,
                ACL: 'private'
              }));

              // Configure CORS for browser uploads
              console.log('Configuring CORS...');
              await s3.send(new PutBucketCorsCommand({
                Bucket: bucketName,
                CORSConfiguration: {
                  CORSRules: [
                    {
                      AllowedHeaders: ['*'],
                      AllowedMethods: ['GET', 'PUT', 'POST', 'DELETE', 'HEAD'],
                      AllowedOrigins: ['*'],
                      ExposeHeaders: ['ETag', 'x-amz-version-id'],
                      MaxAgeSeconds: 3000
                    }
                  ]
                }
              }));
              
              // Step 2: Create CloudFront OAI
              console.log('Creating CloudFront OAI...');
              const oaiResponse = await cloudfront.send(new CreateCloudFrontOriginAccessIdentityCommand({
                CloudFrontOriginAccessIdentityConfig: {
                  CallerReference: `amply-${artistName}-${Date.now()}`,
                  Comment: `Amply OAI for ${artistName}`
                }
              }));
              
              const oaiId = oaiResponse.CloudFrontOriginAccessIdentity.Id;
              const oaiArn = oaiResponse.CloudFrontOriginAccessIdentity.S3CanonicalUserId;
              
              // Step 3: Create bucket policy for CloudFront OAI
              const bucketPolicy = {
                Version: '2012-10-17',
                Statement: [{
                  Effect: 'Allow',
                  Principal: {
                    CanonicalUser: oaiArn
                  },
                  Action: 's3:GetObject',
                  Resource: `arn:aws:s3:::${bucketName}/*`
                }]
              };
              
              await s3.send(new PutBucketPolicyCommand({
                Bucket: bucketName,
                Policy: JSON.stringify(bucketPolicy)
              }));
              
              // Step 4: Create CloudFront distribution
              console.log('Creating CloudFront distribution...');
              const cfResponse = await cloudfront.send(new CreateDistributionCommand({
                DistributionConfig: {
                  Enabled: true,
                  CallerReference: `amply-${artistName}-${Date.now()}`,
                  Comment: `Amply CDN for ${artistName}`,
                  DefaultCacheBehavior: {
                    ViewerProtocolPolicy: 'https-only',
                    TargetOriginId: 's3-origin',
                    TrustedSigners: {
                      Enabled: false,
                      Quantity: 0
                    },
                    ForwardedValues: {
                      QueryString: false,
                      Cookies: { Forward: 'none' }
                    },
                    MinTTL: 0
                  },
                  Origins: {
                    Quantity: 1,
                    Items: [{
                      Id: 's3-origin',
                      DomainName: `${bucketName}.s3.amazonaws.com`,
                      S3OriginConfig: {
                        OriginAccessIdentity: `origin-access-identity/cloudfront/${oaiId}`
                      }
                    }]
                  }
                }
              }));
              
              const cloudfrontDomain = cfResponse.Distribution.DomainName;
              
              // Step 5: Create IAM role for artist uploads
              console.log('Creating IAM role...');
              const roleName = `AmplyAccessRole-${artistName}`;
              
              const rolePolicy = {
                Version: '2012-10-17',
                Statement: [{
                  Effect: 'Allow',
                  Action: ['s3:PutObject', 's3:GetObject', 's3:ListBucket', 's3:DeleteObject'],
                  Resource: [
                    `arn:aws:s3:::${bucketName}`,
                    `arn:aws:s3:::${bucketName}/*`
                  ]
                }]
              };
              
              const roleDoc = {
                Version: '2012-10-17',
                Statement: [{
                  Effect: 'Allow',
                  Principal: {
                    AWS: `arn:aws:iam::${accountId}:root`
                  },
                  Action: 'sts:AssumeRole'
                }]
              };
              
              const roleResponse = await iam.send(new CreateRoleCommand({
                RoleName: roleName,
                AssumeRolePolicyDocument: JSON.stringify(roleDoc),
                Description: `Amply access role for ${artistName}`
              }));
              
              const roleArn = roleResponse.Role.Arn;
              
              await iam.send(new PutRolePolicyCommand({
                RoleName: roleName,
                PolicyName: 'AmplyS3Access',
                PolicyDocument: JSON.stringify(rolePolicy)
              }));
              
              // Step 6: Call Amply callback endpoint
              console.log('Registering with Amply...');
              
              const callbackToken = `amply-setup-${artistId}-${Date.now()}`;
              
              const callbackData = {
                artistId: artistId,
                provider: 'aws',
                outputs: {
                  BucketName: bucketName,
                  CloudFrontDomain: cloudfrontDomain,
                  RoleArn: roleArn
                },
                callback_token: callbackToken,
                callback_timestamp: new Date().toISOString()
              };
              
              await makeHttpRequest(
                process.env.AMPLY_API_ENDPOINT,
                'POST',
                callbackData
              );
              
              console.log('✅ Setup complete!');
              
              // Send success response to CloudFormation
              const responseData = {
                Status: 'SUCCESS',
                PhysicalResourceId: artistId,
                Data: {
                  BucketName: bucketName,
                  CloudFrontDomain: cloudfrontDomain,
                  RoleArn: roleArn
                }
              };
              
              await sendCfnResponse(event, responseData);
              
            } catch (error) {
              console.error('❌ Setup failed:', error);
              const responseData = {
                Status: 'FAILED',
                PhysicalResourceId: event.PhysicalResourceId || 'unknown',
                Reason: error.message
              };
              
              await sendCfnResponse(event, responseData);
            }
          };

          async function getAccountId() {
            const sts = new AWS.STS();
            const identity = await sts.getCallerIdentity().promise();
            return identity.Account;
          }

          function sendCfnResponse(event, responseData) {
            return new Promise((resolve, reject) => {
              const responseBody = JSON.stringify({
                Status: responseData.Status,
                Reason: responseData.Reason || '',
                PhysicalResourceId: responseData.PhysicalResourceId,
                StackId: event.StackId,
                RequestId: event.RequestId,
                LogicalResourceId: event.LogicalResourceId,
                Data: responseData.Data || {}
              });

              const options = new URL(event.ResponseURL);
              const req = https.request({
                hostname: options.hostname,
                path: options.pathname + options.search,
                method: 'PUT',
                headers: {
                  'Content-Type': '',
                  'Content-Length': Buffer.byteLength(responseBody)
                }
              }, (res) => {
                if (res.statusCode !== 200) {
                  console.error(`CloudFormation response failed with status ${res.statusCode}`);
                }
                resolve();
              });

              req.on('error', (error) => {
                console.error('Error sending CloudFormation response:', error);
                reject(error);
              });

              req.write(responseBody);
              req.end();
            });
          }

          function makeHttpRequest(url, method, data) {
            return new Promise((resolve, reject) => {
              const options = new URL(url);
              const postData = JSON.stringify(data);
              
              const req = https.request({
                hostname: options.hostname,
                path: options.pathname + options.search,
                method: method,
                headers: {
                  'Content-Type': 'application/json',
                  'Content-Length': Buffer.byteLength(postData)
                }
              }, (res) => {
                let responseData = '';
                res.on('data', chunk => responseData += chunk);
                res.on('end', () => resolve({
                  statusCode: res.statusCode,
                  body: responseData
                }));
              });
              
              req.on('error', reject);
              req.write(postData);
              req.end();
            });
          }

  # Custom resource to invoke the Lambda
  SetupExecution:
    Type: Custom::AmplySetup
    Properties:
      ServiceToken: !GetAtt SetupLambda.Arn
      ArtistName: !Ref ArtistName
      ArtistId: !Ref ArtistId
      Account: !Ref "AWS::AccountId"

Outputs:
  BucketName:
    Description: S3 bucket for artist content
    Value: !GetAtt SetupExecution.BucketName

  CloudFrontDomain:
    Description: CloudFront distribution domain
    Value: !GetAtt SetupExecution.CloudFrontDomain

  RoleArn:
    Description: IAM role for artist uploads
    Value: !GetAtt SetupExecution.RoleArn

  Status:
    Description: Setup status
    Value: "Setup complete - infrastructure created and registered with Amply"
