AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB Tables for Amply Platform"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  # ============================================================
  # TABLE 1: amply-users
  # Stores user profiles (listeners and artists)
  # ============================================================
  AmplyUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "amply-users-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        # Search by username
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        # Search by email
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================================
  # TABLE 2: amply-listen-history
  # Tracks every listen for payment calculations
  # CRITICAL: songId is hash key for payment queries
  # ============================================================
  AmplyListenHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "amply-listen-history-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: songId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: userId
          AttributeType: S
        - AttributeName: artistId
          AttributeType: S
      KeySchema:
        # Partition by songId (for payment queries: "give me all listens for song1")
        # Sort by timestamp (latest first)
        - AttributeName: songId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        # Query "all listens by userId" (user listening history)
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # Query "all listens for artist" (artist analytics)
        - IndexName: ArtistIdIndex
          KeySchema:
            - AttributeName: artistId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiryTime
        Enabled: true # Auto-delete old records after 1 year for cost savings
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================================
  # TABLE 3: amply-playlists
  # User-created playlists (public and private)
  # ============================================================
  AmplyPlaylistsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "amply-playlists-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: playlistId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: isPublic
          AttributeType: N # 1 for true, 0 for false
      KeySchema:
        - AttributeName: playlistId
          KeyType: HASH
      GlobalSecondaryIndexes:
        # Query "all playlists by user"
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        # Query "all public playlists" (for discovery)
        - IndexName: PublicPlaylistsIndex
          KeySchema:
            - AttributeName: isPublic
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================================
  # TABLE 4: amply-artist-config
  # Private artist infrastructure (S3 bucket, IAM role)
  # DO NOT expose to frontend
  # ============================================================
  AmplyArtistConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "amply-artist-config-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: artistId
          AttributeType: S
      KeySchema:
        - AttributeName: artistId
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================================
  # TABLE 5: amply-follows (optional, for followers tracking)
  # Track which users follow which artists
  # ============================================================
  AmplyFollowsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "amply-follows-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: artistId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: artistId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        # Query "who follows artistId"
        - IndexName: ArtistFollowersIndex
          KeySchema:
            - AttributeName: artistId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  UsersTableName:
    Description: Name of the users table
    Value: !Ref AmplyUsersTable
    Export:
      Name: !Sub "${AWS::StackName}-UsersTable"

  ListenHistoryTableName:
    Description: Name of the listen history table
    Value: !Ref AmplyListenHistoryTable
    Export:
      Name: !Sub "${AWS::StackName}-ListenHistoryTable"

  PlaylistsTableName:
    Description: Name of the playlists table
    Value: !Ref AmplyPlaylistsTable
    Export:
      Name: !Sub "${AWS::StackName}-PlaylistsTable"

  ArtistConfigTableName:
    Description: Name of the artist config table
    Value: !Ref AmplyArtistConfigTable
    Export:
      Name: !Sub "${AWS::StackName}-ArtistConfigTable"

  FollowsTableName:
    Description: Name of the follows table
    Value: !Ref AmplyFollowsTable
    Export:
      Name: !Sub "${AWS::StackName}-FollowsTable"
